spring:
  datasource:
    url: jdbc:mysql://localhost:3306/netfaulttracker?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
        use_sql_comments: true
  mvc:
    view:
      prefix: /
      suffix: .html
  web:
    resources:
      static-locations: classpath:/static/


server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      force: true

logging:
  level:
    root: INFO
    com.netcoretech.netfaulttracker: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql: TRACE
    org.springframework.orm.jpa: DEBUG
    org.springframework.transaction: DEBUG
  file:
    name: logs/netfaulttracker.log
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when-authorized

netfaulttracker:
  default-page-size: 20
  max-page-size: 100
  admin:
  # 여기에 관리자 관련 설정을 추가할 수 있습니다